### PR TITLE
feature: make it possible to hide player control buttons

### PR DESCRIPTION
**Pull request by punxaphil**

### CODE REVIEW

**Comment by thlucas1** [comment]
I can't figure out how to get the changes from your e6513e9 commit into my forked repository to test them.

**Comment by punxaphil** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-with-the-github-cli

Something like this:
```
gh repo sync thlucas1/featurePlayerControlsHideShow -b featurePlayerControlsHideShow --force
```

**Comment by punxaphil** [comment]
You might be able to do it in the GUI as well, not sure:
https://github.com/thlucas1/maxi-media-player/tree/featurePlayerControlsHideShow

**Comment by thlucas1** [comment]
Ok ... I was able to sync the changes up and test them in my Bose SoundTouch environment.  I did the following:

__Single Player Mode__
- verified that player section control buttons could be hidden / shown (power, next track, previous track, repeat, shuffle) as configured.
- verified that volume section power button was hidden / shown as configured.
- verified that after powering off, the power button was shown on the player section if media player supports turn_on service and power button is configured to be shown.

__Group Player Mode__
- verified that player section control buttons could be hidden / shown (power, next track, previous track, repeat, shuffle) as configured.
- verified that volume section power button was hidden / shown as configured for all media players.
- verified that after powering off, the power button was shown on the player section if media player supports turn_on service and power button is configured to be shown.

__Other Thoughts__
Not related to your changes, but while you are in there ...
The volumes section `volume step up / down` and `volume cogwheel` icons are not styled likes the mute and power icons, which makes them look odd or out of place.  Example:
image

Other than that, it all looks great!  Thanks.

**Comment by punxaphil** [comment]
That looks odd. Do you have custom styling?

**Comment by thlucas1** [comment]
I did notice something else though after powering off the devices.  

It seems that the volume slider displays 100% when the device is powered off.  It does this on both the Volumes section and Grouping section.  The Volumes section also displays a "0%NaN%" value.  It makes me think that when I power the speaker back on that the volume will be 100%, but it does not - it powers back on at the previous volume.  Is there a way to just leave the volume display at the last known volume level when powered off?  Or maybe set it to zero (instead of 100) if powered off?

image
image

**Comment by punxaphil** [comment]
I thought I was hiding that when off. Can you see if you can fix it?

**Comment by thlucas1** [comment]
Submitted [PR #23](https://github.com/punxaphil/maxi-media-player/pull/23)

**Comment by punxaphil** [comment]
https://github.com/punxaphil/maxi-media-player/releases/tag/v1.6.0

**Pull request closed without merging**
